# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommendpb/recommend.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recommendpb/recommend.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1brecommendpb/recommend.proto\"S\n\x10RecommendRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x19\n\x05genre\x18\x02 \x01(\x0e\x32\n.BookGenre\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"4\n\x12\x42ookRecommendation\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\"A\n\x11RecommendResponse\x12,\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x13.BookRecommendation*t\n\tBookGenre\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x13\n\x0fSCIENCE_FICTION\x10\x01\x12\x0f\n\x0bNON_FICTION\x10\x02\x12\x0b\n\x07\x46\x41NTASY\x10\x03\x12\x0b\n\x07MYSTERY\x10\x04\x12\x0b\n\x07ROMANCE\x10\x05\x12\r\n\tBIOGRAPHY\x10\x06\x32\x44\n\x0eRecommendation\x12\x32\n\tRecommend\x12\x11.RecommendRequest\x1a\x12.RecommendResponseb\x06proto3'
)

_BOOKGENRE = _descriptor.EnumDescriptor(
  name='BookGenre',
  full_name='BookGenre',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SCIENCE_FICTION', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NON_FICTION', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FANTASY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MYSTERY', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ROMANCE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BIOGRAPHY', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=237,
  serialized_end=353,
)
_sym_db.RegisterEnumDescriptor(_BOOKGENRE)

BookGenre = enum_type_wrapper.EnumTypeWrapper(_BOOKGENRE)
UNKNOWN = 0
SCIENCE_FICTION = 1
NON_FICTION = 2
FANTASY = 3
MYSTERY = 4
ROMANCE = 5
BIOGRAPHY = 6



_RECOMMENDREQUEST = _descriptor.Descriptor(
  name='RecommendRequest',
  full_name='RecommendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='RecommendRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='genre', full_name='RecommendRequest.genre', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_results', full_name='RecommendRequest.max_results', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=114,
)


_BOOKRECOMMENDATION = _descriptor.Descriptor(
  name='BookRecommendation',
  full_name='BookRecommendation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='book_id', full_name='BookRecommendation.book_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='BookRecommendation.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=168,
)


_RECOMMENDRESPONSE = _descriptor.Descriptor(
  name='RecommendResponse',
  full_name='RecommendResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='recommendations', full_name='RecommendResponse.recommendations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=235,
)

_RECOMMENDREQUEST.fields_by_name['genre'].enum_type = _BOOKGENRE
_RECOMMENDRESPONSE.fields_by_name['recommendations'].message_type = _BOOKRECOMMENDATION
DESCRIPTOR.message_types_by_name['RecommendRequest'] = _RECOMMENDREQUEST
DESCRIPTOR.message_types_by_name['BookRecommendation'] = _BOOKRECOMMENDATION
DESCRIPTOR.message_types_by_name['RecommendResponse'] = _RECOMMENDRESPONSE
DESCRIPTOR.enum_types_by_name['BookGenre'] = _BOOKGENRE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecommendRequest = _reflection.GeneratedProtocolMessageType('RecommendRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDREQUEST,
  '__module__' : 'recommendpb.recommend_pb2'
  # @@protoc_insertion_point(class_scope:RecommendRequest)
  })
_sym_db.RegisterMessage(RecommendRequest)

BookRecommendation = _reflection.GeneratedProtocolMessageType('BookRecommendation', (_message.Message,), {
  'DESCRIPTOR' : _BOOKRECOMMENDATION,
  '__module__' : 'recommendpb.recommend_pb2'
  # @@protoc_insertion_point(class_scope:BookRecommendation)
  })
_sym_db.RegisterMessage(BookRecommendation)

RecommendResponse = _reflection.GeneratedProtocolMessageType('RecommendResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDRESPONSE,
  '__module__' : 'recommendpb.recommend_pb2'
  # @@protoc_insertion_point(class_scope:RecommendResponse)
  })
_sym_db.RegisterMessage(RecommendResponse)



_RECOMMENDATION = _descriptor.ServiceDescriptor(
  name='Recommendation',
  full_name='Recommendation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=355,
  serialized_end=423,
  methods=[
  _descriptor.MethodDescriptor(
    name='Recommend',
    full_name='Recommendation.Recommend',
    index=0,
    containing_service=None,
    input_type=_RECOMMENDREQUEST,
    output_type=_RECOMMENDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECOMMENDATION)

DESCRIPTOR.services_by_name['Recommendation'] = _RECOMMENDATION

# @@protoc_insertion_point(module_scope)
